{{ range .Values.images }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    {{- include "bot.labels" $ | replace "bot" .name | nindent 4 }}
spec:
  {{- if and (not $.Values.autoscaling.enabled) (eq .name $.Chart.Name) }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bot.selectorLabels" $ | replace "bot" .name | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bot.selectorLabels" $ | replace "bot" .name | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bot.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- with .command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- $containerName := .name }}
          {{- range $.Values.configmaps }}
          {{- if and (eq .container $containerName) .needsMounting }}
          volumeMounts:
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
          {{- end }}
          {{- end }}
      volumes:
        {{- range $.Values.configmaps }}
        {{- if and (eq .container $containerName) .needsMounting }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
            items:
              - key: {{ keys .data | first }}
                path: {{ keys .data | first }}
        {{- end }}
        {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}